// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"github.com/google/uuid"
)

type ToDo struct {
	ID          uuid.UUID
	Title       string
	Description string
	Completed   bool
}
